### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.Blog#6]
## Goals:
* Automatically provide AMP version of blog entries
* Provide sane defaults so that integrators have minimal work
* Keep every part of the alternate rendering configurable
* Don't break anything by adding this feature

## Tasks:
- [x] Provide alternative rendering path for blog entries
- [x] Provide header link to AMP version of blog entries
- [x] Provide micro data in header of blog entries
- [x] Link necessary stylesheets and scripts in AMP version of blog entries
- [x] Create documentation for customization
- [x] Create documentation on how to disable it
